# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvoice.proto\x12\x05voice\" \n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"\x19\n\tTextChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\"3\n\x12TranscriptionChunk\x12\x1d\n\x15partial_transcription\x18\x01 \x01(\t\"D\n\x13TextToSpeechRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\r\n\x05voice\x18\x03 \x01(\t\"*\n\x14TextToSpeechResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\")\n\x13SpeechToTextRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"0\n\x14SpeechToTextResponse\x12\x18\n\x10transcribed_text\x18\x01 \x01(\t2\xc6\x02\n\x13TextToSpeechService\x12N\n\x13\x43onvertTextToSpeech\x12\x1a.voice.TextToSpeechRequest\x1a\x1b.voice.TextToSpeechResponse\x12\x45\n\x12StreamTextToSpeech\x12\x1a.voice.TextToSpeechRequest\x1a\x11.voice.AudioChunk0\x01\x12L\n\x19StreamTextToSpeechRequest\x12\x10.voice.TextChunk\x1a\x1b.voice.TextToSpeechResponse(\x01\x12J\n\x1fStreamTextToSpeechBidirectional\x12\x10.voice.TextChunk\x1a\x11.voice.AudioChunk(\x01\x30\x01\x32\xd8\x02\n\x13SpeechToTextService\x12N\n\x13\x43onvertSpeechToText\x12\x1a.voice.SpeechToTextRequest\x1a\x1b.voice.SpeechToTextResponse\x12M\n\x12StreamSpeechToText\x12\x1a.voice.SpeechToTextRequest\x1a\x19.voice.TranscriptionChunk0\x01\x12M\n\x19StreamSpeechToTextRequest\x12\x11.voice.AudioChunk\x1a\x1b.voice.SpeechToTextResponse(\x01\x12S\n\x1fStreamSpeechToTextBidirectional\x12\x11.voice.AudioChunk\x1a\x19.voice.TranscriptionChunk(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOCHUNK']._serialized_start=22
  _globals['_AUDIOCHUNK']._serialized_end=54
  _globals['_TEXTCHUNK']._serialized_start=56
  _globals['_TEXTCHUNK']._serialized_end=81
  _globals['_TRANSCRIPTIONCHUNK']._serialized_start=83
  _globals['_TRANSCRIPTIONCHUNK']._serialized_end=134
  _globals['_TEXTTOSPEECHREQUEST']._serialized_start=136
  _globals['_TEXTTOSPEECHREQUEST']._serialized_end=204
  _globals['_TEXTTOSPEECHRESPONSE']._serialized_start=206
  _globals['_TEXTTOSPEECHRESPONSE']._serialized_end=248
  _globals['_SPEECHTOTEXTREQUEST']._serialized_start=250
  _globals['_SPEECHTOTEXTREQUEST']._serialized_end=291
  _globals['_SPEECHTOTEXTRESPONSE']._serialized_start=293
  _globals['_SPEECHTOTEXTRESPONSE']._serialized_end=341
  _globals['_TEXTTOSPEECHSERVICE']._serialized_start=344
  _globals['_TEXTTOSPEECHSERVICE']._serialized_end=670
  _globals['_SPEECHTOTEXTSERVICE']._serialized_start=673
  _globals['_SPEECHTOTEXTSERVICE']._serialized_end=1017
# @@protoc_insertion_point(module_scope)
